//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavTechAssessmentAPI.DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int OrderId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual item item { get; set; }
    }
}
